import authService from "./auth.service";
import updateuser from "./user.service";
import contactSevice from "./contact.service";
import notifycationsService from "./notifycation.service";
import mesageService from "./message.service";
import groupChatService from "./groupChat.service";
export const auth = authService;
export const user = updateuser;
export const contact = contactSevice;
export const notifycation = notifycationsService;
export const message = mesageService;
export const groupChat = groupChatService;
