import authValidation from "./authValidation";
import userValidation from "./userValidation";
import contactValidation from "./contactValidation";
import checkValidate from "./messageValidation";
import groupChatValidation from "./groupChatValidation";
export const authValid = authValidation;
export const userValid = userValidation;
export const contactValid = contactValidation;
export const messageValid = checkValidate;
export const groupChatValid = groupChatValidation;
